before_script: "psql -c 'create database rapns_test;' -U postgres >/dev/null"
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
gemfile:
  - Gemfile
  - Gemfile.rails-4.0
env: QUALITY=true

matrix:
  include:
    - rvm: 1.9.3
      gemfile: Gemfile.rails-4.0
      env: QUALITY=false
    - rvm: 2.0.0
      gemfile: Gemfile.rails-4.0
      env: QUALITY=false
    - rvm: 2.0.0
      gemfile: Gemfile
      env: ADAPTER=sqlite3
  exclude:
    - rvm: 1.9.3
      gemfile: Gemfile.rails-4.0
      env: QUALITY=true
    - rvm: 2.0.0
      gemfile: Gemfile.rails-4.0
      env: QUALITY=true
    - rvm: jruby-19mode
      gemfile: Gemfile.rails-4.0
      env: QUALITY=true
    - rvm: rbx-19mode
      gemfile: Gemfile.rails-4.0
      env: QUALITY=true
  allow_failures:
    - rvm: rbx-19mode
    - rvm: jruby-19mode
