# postgresql is the default if no ADAPTER environment variable is set when running specs.

postgresql:
  adapter: postgresql
  database: rapns_test
  host: localhost
  username: postgres
  password: ""

jdbcpostgresql:
  adapter: jdbcpostgresql
  database: rapns_test
  host: localhost
  username: postgres
  password: ""

mysql2:
  adapter: mysql2
  database: rapns_test
  host: localhost
  username: rapns_test
  password: ""
  encoding: utf8

jdbcmysql:
  adapter: jdbcmysql
  database: rapns_test
  host: localhost
  username: rapns_test
  password: ""
  encoding: utf8

jdbch2:
  adapter: h2
  url: jdbc:h2:file:/tmp/rapns_test;AUTO_SERVER=TRUE
  username: rapns_test
  password: ""
  pool: 128
  timeout: 5000
  encoding: utf8

sqlite3:
  adapter: sqlite3
  database: spec/tmp/rapns_test.sqlite3
